default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [-Werror, -i, --style=llvm]
      - id: clang-tidy
        args:
          [
            --fix,
            --fix-errors,
            --fix-notes,
            --format-style=llvm,
            -p=build/compile_commands.json,
          ]
      - id: oclint
        args: [-p=build/compile_commands.json]
      - id: cppcheck
      - id: cpplint
      - id: include-what-you-use
        args: ["-Xiwyu", "--error=1"]
