default_install_hook_types: [pre-commit, commit-msg]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.27.0
    hooks:
      - id: commitizen
  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -Werror -i --style=llvm
        language: system
        types_or: [c++]
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy --fix --fix-errors --fix-notes --format-style=llvm -p=build/compile_commands.json
        language: system
        types_or: [c++]
      - id: cppcheck
        name: cppcheck
        entry: cppcheck -Iinclude/ --suppress=unmatchedSuppression --suppress=missingIncludeSystem --suppress=unusedFunction --suppress=unknownMacro
        language: system
        types_or: [c++]
      - id: cpplint
        name: cpplint
        entry: cpplint --filter=-legal/copyright,-whitespace/comments,-whitespace/blank_line,-build/include_order,-build/include_subdir
        language: system
        types_or: [c++]
      - id: include-what-you-use
        name: include-what-you-use
        entry: include-what-you-use -Xiwyu --error=1 -Iinclude/ -std=c++23
        language: system
        types_or: [c++]
